import { OPENAI_API_KEY as ENV_OPENAI_KEY, FIREBASE_API_KEY as ENV_FIREBASE_KEY, FIREBASE_APP_ID, FIREBASE_MEASUREMENT_ID, FIREBASE_PROJECT_ID } from '@env';

export const ENV = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY || '',
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID || '',
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID || '',
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || '',
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET || '',
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN || '',
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  API_URL: 'https://api.openai.com/v1/audio',
  MAX_FILE_SIZE: 25 * 1024 * 1024,
};
